// Code generated by protoc-gen-go. DO NOT EDIT.
// source: schema.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type OperationCode int32

const (
	OperationCode_INFORMATION         OperationCode = 0
	OperationCode_REGISTER_DEVICE     OperationCode = 1
	OperationCode_GENERATE_CHALLENGE  OperationCode = 2
	OperationCode_AUTHORIZE           OperationCode = 3
	OperationCode_REGISTER_IDENTITY   OperationCode = 4
	OperationCode_LINK_IDENTITY       OperationCode = 5
	OperationCode_UNLINK_IDENTITY     OperationCode = 6
	OperationCode_LIST_LINKED_DEVICES OperationCode = 7
	OperationCode_UPDATE_DEVICE       OperationCode = 8
	OperationCode_UPDATE_IDENTITY     OperationCode = 9
	OperationCode_UPDATE_KEYS         OperationCode = 10
	OperationCode_QUERY_IDENTITIES    OperationCode = 11
	OperationCode_QUERY_CHATS         OperationCode = 12
	OperationCode_CREATE_CHAT         OperationCode = 13
	OperationCode_JOIN_CHAT           OperationCode = 14
	OperationCode_PENDING_CHATS       OperationCode = 15
	OperationCode_CHAT_MANAGEMENT     OperationCode = 16
	OperationCode_SEND_MESSAGE        OperationCode = 17
	OperationCode_QUERY_MESSAGES      OperationCode = 18
	OperationCode_EDIT_MESSAGE        OperationCode = 19
	OperationCode_LISTEN_FOR_EVENTS   OperationCode = 20
)

var OperationCode_name = map[int32]string{
	0:  "INFORMATION",
	1:  "REGISTER_DEVICE",
	2:  "GENERATE_CHALLENGE",
	3:  "AUTHORIZE",
	4:  "REGISTER_IDENTITY",
	5:  "LINK_IDENTITY",
	6:  "UNLINK_IDENTITY",
	7:  "LIST_LINKED_DEVICES",
	8:  "UPDATE_DEVICE",
	9:  "UPDATE_IDENTITY",
	10: "UPDATE_KEYS",
	11: "QUERY_IDENTITIES",
	12: "QUERY_CHATS",
	13: "CREATE_CHAT",
	14: "JOIN_CHAT",
	15: "PENDING_CHATS",
	16: "CHAT_MANAGEMENT",
	17: "SEND_MESSAGE",
	18: "QUERY_MESSAGES",
	19: "EDIT_MESSAGE",
	20: "LISTEN_FOR_EVENTS",
}

var OperationCode_value = map[string]int32{
	"INFORMATION":         0,
	"REGISTER_DEVICE":     1,
	"GENERATE_CHALLENGE":  2,
	"AUTHORIZE":           3,
	"REGISTER_IDENTITY":   4,
	"LINK_IDENTITY":       5,
	"UNLINK_IDENTITY":     6,
	"LIST_LINKED_DEVICES": 7,
	"UPDATE_DEVICE":       8,
	"UPDATE_IDENTITY":     9,
	"UPDATE_KEYS":         10,
	"QUERY_IDENTITIES":    11,
	"QUERY_CHATS":         12,
	"CREATE_CHAT":         13,
	"JOIN_CHAT":           14,
	"PENDING_CHATS":       15,
	"CHAT_MANAGEMENT":     16,
	"SEND_MESSAGE":        17,
	"QUERY_MESSAGES":      18,
	"EDIT_MESSAGE":        19,
	"LISTEN_FOR_EVENTS":   20,
}

func (x OperationCode) String() string {
	return proto.EnumName(OperationCode_name, int32(x))
}

func (OperationCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_1c5fb4d8cc22d66a, []int{0}
}

type Message struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c5fb4d8cc22d66a, []int{0}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

type Reply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Reply) Reset()         { *m = Reply{} }
func (m *Reply) String() string { return proto.CompactTextString(m) }
func (*Reply) ProtoMessage()    {}
func (*Reply) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c5fb4d8cc22d66a, []int{1}
}

func (m *Reply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Reply.Unmarshal(m, b)
}
func (m *Reply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Reply.Marshal(b, m, deterministic)
}
func (m *Reply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Reply.Merge(m, src)
}
func (m *Reply) XXX_Size() int {
	return xxx_messageInfo_Reply.Size(m)
}
func (m *Reply) XXX_DiscardUnknown() {
	xxx_messageInfo_Reply.DiscardUnknown(m)
}

var xxx_messageInfo_Reply proto.InternalMessageInfo

func init() {
	proto.RegisterEnum("OperationCode", OperationCode_name, OperationCode_value)
	proto.RegisterType((*Message)(nil), "Message")
	proto.RegisterType((*Reply)(nil), "Reply")
}

func init() { proto.RegisterFile("schema.proto", fileDescriptor_1c5fb4d8cc22d66a) }

var fileDescriptor_1c5fb4d8cc22d66a = []byte{
	// 337 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x91, 0xcf, 0x6e, 0xe2, 0x30,
	0x10, 0xc6, 0x77, 0xf9, 0xbb, 0x0c, 0x04, 0x06, 0xc3, 0xee, 0xde, 0x39, 0xee, 0x61, 0x2f, 0x7d,
	0x02, 0x37, 0x19, 0x82, 0x4b, 0x32, 0xa1, 0xb6, 0x83, 0x04, 0x97, 0x08, 0xda, 0xa8, 0xad, 0xd4,
	0x36, 0x11, 0x70, 0xe9, 0x33, 0xf5, 0x25, 0x2b, 0x93, 0x94, 0xaa, 0xb7, 0xe4, 0xa7, 0x6f, 0xe6,
	0xe7, 0xcf, 0x86, 0xc1, 0xf1, 0xee, 0x31, 0x7f, 0xd9, 0xfd, 0x2f, 0x0f, 0xc5, 0xa9, 0x98, 0xf5,
	0xa0, 0x1b, 0xe7, 0xc7, 0xe3, 0xee, 0x21, 0x9f, 0x75, 0xa1, 0xad, 0xf3, 0xf2, 0xf9, 0xed, 0xdf,
	0x7b, 0x13, 0xbc, 0xa4, 0xcc, 0x0f, 0xbb, 0xd3, 0x53, 0xf1, 0xea, 0x17, 0xf7, 0xb9, 0x18, 0x41,
	0x5f, 0xf1, 0x3c, 0xd1, 0xb1, 0xb4, 0x2a, 0x61, 0xfc, 0x21, 0x26, 0x30, 0xd2, 0x14, 0x2a, 0x63,
	0x49, 0x67, 0x01, 0xad, 0x95, 0x4f, 0xf8, 0x53, 0xfc, 0x01, 0x11, 0x12, 0x93, 0x96, 0x96, 0x32,
	0x7f, 0x21, 0xa3, 0x88, 0x38, 0x24, 0x6c, 0x08, 0x0f, 0x7a, 0x32, 0xb5, 0x8b, 0x44, 0xab, 0x2d,
	0x61, 0x53, 0xfc, 0x86, 0xf1, 0x65, 0x56, 0x05, 0xc4, 0x56, 0xd9, 0x0d, 0xb6, 0xc4, 0x18, 0xbc,
	0x48, 0xf1, 0xf2, 0x0b, 0xb5, 0x9d, 0x25, 0xe5, 0xef, 0xb0, 0x23, 0xfe, 0xc2, 0x24, 0x52, 0xc6,
	0x66, 0x8e, 0x53, 0x50, 0xdb, 0x0d, 0x76, 0xdd, 0x82, 0x74, 0x15, 0x38, 0x79, 0x7d, 0xa2, 0x5f,
	0xe7, 0x05, 0x15, 0xba, 0x2c, 0xe8, 0xb9, 0x32, 0x35, 0x5c, 0xd2, 0xc6, 0x20, 0x88, 0x29, 0xe0,
	0x6d, 0x4a, 0x7a, 0xf3, 0x19, 0x52, 0x64, 0xb0, 0xef, 0x62, 0x15, 0xf5, 0x17, 0xd2, 0x1a, 0x1c,
	0x38, 0xe0, 0x6b, 0xaa, 0xcb, 0x59, 0xf4, 0x5c, 0xaf, 0x9b, 0x44, 0x71, 0xf5, 0x3b, 0x74, 0xfe,
	0x15, 0x71, 0xa0, 0x38, 0xac, 0x47, 0x46, 0xce, 0xef, 0x3e, 0xb3, 0x58, 0xb2, 0x0c, 0x29, 0x26,
	0xb6, 0x88, 0x02, 0x61, 0x60, 0x88, 0x83, 0x2c, 0x26, 0x63, 0x64, 0x48, 0x38, 0x16, 0x02, 0x86,
	0x95, 0xaa, 0x46, 0x06, 0x85, 0x4b, 0x51, 0xa0, 0xec, 0x25, 0x35, 0x71, 0xf7, 0xe6, 0x8a, 0x13,
	0x67, 0xf3, 0x44, 0x67, 0xb4, 0x26, 0xb6, 0x06, 0xa7, 0xd7, 0xad, 0x6d, 0xa3, 0xdc, 0xef, 0x3b,
	0xe7, 0xe7, 0xbc, 0xfa, 0x08, 0x00, 0x00, 0xff, 0xff, 0x4b, 0xee, 0x91, 0xdd, 0xde, 0x01, 0x00,
	0x00,
}
