// Code generated by protoc-gen-go. DO NOT EDIT.
// source: schema.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type OperationCode int32

const (
	OperationCode_INFORMATION         OperationCode = 0
	OperationCode_REGISTER_DEVICE     OperationCode = 1
	OperationCode_GENERATE_CHALLENGE  OperationCode = 2
	OperationCode_AUTHORIZE           OperationCode = 3
	OperationCode_REGISTER_IDENTITY   OperationCode = 4
	OperationCode_LINK_IDENTITY       OperationCode = 5
	OperationCode_UNLINK_IDENTITY     OperationCode = 6
	OperationCode_LIST_LINKED_DEVICES OperationCode = 7
	OperationCode_UPDATE_DEVICE       OperationCode = 8
	OperationCode_UPDATE_IDENTITY     OperationCode = 9
	OperationCode_UPDATE_KEYS         OperationCode = 10
	OperationCode_QUERY_IDENTITIES    OperationCode = 11
	OperationCode_QUERY_CHATS         OperationCode = 12
	OperationCode_CREATE_CHAT         OperationCode = 13
	OperationCode_JOIN_CHAT           OperationCode = 14
	OperationCode_PENDING_CHATS       OperationCode = 15
	OperationCode_CHAT_MANAGEMENT     OperationCode = 16
	OperationCode_SEND_MESSAGE        OperationCode = 17
	OperationCode_QUERY_MESSAGES      OperationCode = 18
	OperationCode_EDIT_MESSAGE        OperationCode = 19
	OperationCode_LISTEN_FOR_EVENTS   OperationCode = 20
)

var OperationCode_name = map[int32]string{
	0:  "INFORMATION",
	1:  "REGISTER_DEVICE",
	2:  "GENERATE_CHALLENGE",
	3:  "AUTHORIZE",
	4:  "REGISTER_IDENTITY",
	5:  "LINK_IDENTITY",
	6:  "UNLINK_IDENTITY",
	7:  "LIST_LINKED_DEVICES",
	8:  "UPDATE_DEVICE",
	9:  "UPDATE_IDENTITY",
	10: "UPDATE_KEYS",
	11: "QUERY_IDENTITIES",
	12: "QUERY_CHATS",
	13: "CREATE_CHAT",
	14: "JOIN_CHAT",
	15: "PENDING_CHATS",
	16: "CHAT_MANAGEMENT",
	17: "SEND_MESSAGE",
	18: "QUERY_MESSAGES",
	19: "EDIT_MESSAGE",
	20: "LISTEN_FOR_EVENTS",
}

var OperationCode_value = map[string]int32{
	"INFORMATION":         0,
	"REGISTER_DEVICE":     1,
	"GENERATE_CHALLENGE":  2,
	"AUTHORIZE":           3,
	"REGISTER_IDENTITY":   4,
	"LINK_IDENTITY":       5,
	"UNLINK_IDENTITY":     6,
	"LIST_LINKED_DEVICES": 7,
	"UPDATE_DEVICE":       8,
	"UPDATE_IDENTITY":     9,
	"UPDATE_KEYS":         10,
	"QUERY_IDENTITIES":    11,
	"QUERY_CHATS":         12,
	"CREATE_CHAT":         13,
	"JOIN_CHAT":           14,
	"PENDING_CHATS":       15,
	"CHAT_MANAGEMENT":     16,
	"SEND_MESSAGE":        17,
	"QUERY_MESSAGES":      18,
	"EDIT_MESSAGE":        19,
	"LISTEN_FOR_EVENTS":   20,
}

func (x OperationCode) String() string {
	return proto.EnumName(OperationCode_name, int32(x))
}

func (OperationCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_1c5fb4d8cc22d66a, []int{0}
}

type ErrorCode int32

const (
	ErrorCode_NOT_IMPLEMENTED ErrorCode = 0
)

var ErrorCode_name = map[int32]string{
	0: "NOT_IMPLEMENTED",
}

var ErrorCode_value = map[string]int32{
	"NOT_IMPLEMENTED": 0,
}

func (x ErrorCode) String() string {
	return proto.EnumName(ErrorCode_name, int32(x))
}

func (ErrorCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_1c5fb4d8cc22d66a, []int{1}
}

type Message struct {
	Signature            []byte   `protobuf:"bytes,1,opt,name=signature,proto3" json:"signature,omitempty"`
	Source               []byte   `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	Destination          []byte   `protobuf:"bytes,3,opt,name=destination,proto3" json:"destination,omitempty"`
	Data                 []byte   `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c5fb4d8cc22d66a, []int{0}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

func (m *Message) GetSource() []byte {
	if m != nil {
		return m.Source
	}
	return nil
}

func (m *Message) GetDestination() []byte {
	if m != nil {
		return m.Destination
	}
	return nil
}

func (m *Message) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type Reply struct {
	// Types that are valid to be assigned to Status:
	//	*Reply_Result
	//	*Reply_Error
	Status               isReply_Status `protobuf_oneof:"status"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Reply) Reset()         { *m = Reply{} }
func (m *Reply) String() string { return proto.CompactTextString(m) }
func (*Reply) ProtoMessage()    {}
func (*Reply) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c5fb4d8cc22d66a, []int{1}
}

func (m *Reply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Reply.Unmarshal(m, b)
}
func (m *Reply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Reply.Marshal(b, m, deterministic)
}
func (m *Reply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Reply.Merge(m, src)
}
func (m *Reply) XXX_Size() int {
	return xxx_messageInfo_Reply.Size(m)
}
func (m *Reply) XXX_DiscardUnknown() {
	xxx_messageInfo_Reply.DiscardUnknown(m)
}

var xxx_messageInfo_Reply proto.InternalMessageInfo

type isReply_Status interface {
	isReply_Status()
}

type Reply_Result struct {
	Result []byte `protobuf:"bytes,1,opt,name=result,proto3,oneof"`
}

type Reply_Error struct {
	Error *Error `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*Reply_Result) isReply_Status() {}

func (*Reply_Error) isReply_Status() {}

func (m *Reply) GetStatus() isReply_Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *Reply) GetResult() []byte {
	if x, ok := m.GetStatus().(*Reply_Result); ok {
		return x.Result
	}
	return nil
}

func (m *Reply) GetError() *Error {
	if x, ok := m.GetStatus().(*Reply_Error); ok {
		return x.Error
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Reply) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Reply_Result)(nil),
		(*Reply_Error)(nil),
	}
}

type InformationReply struct {
	Version              string   `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InformationReply) Reset()         { *m = InformationReply{} }
func (m *InformationReply) String() string { return proto.CompactTextString(m) }
func (*InformationReply) ProtoMessage()    {}
func (*InformationReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c5fb4d8cc22d66a, []int{2}
}

func (m *InformationReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InformationReply.Unmarshal(m, b)
}
func (m *InformationReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InformationReply.Marshal(b, m, deterministic)
}
func (m *InformationReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InformationReply.Merge(m, src)
}
func (m *InformationReply) XXX_Size() int {
	return xxx_messageInfo_InformationReply.Size(m)
}
func (m *InformationReply) XXX_DiscardUnknown() {
	xxx_messageInfo_InformationReply.DiscardUnknown(m)
}

var xxx_messageInfo_InformationReply proto.InternalMessageInfo

func (m *InformationReply) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

type Error struct {
	Code                 ErrorCode `protobuf:"varint,1,opt,name=code,proto3,enum=ErrorCode" json:"code,omitempty"`
	Description          string    `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c5fb4d8cc22d66a, []int{3}
}

func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (m *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(m, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetCode() ErrorCode {
	if m != nil {
		return m.Code
	}
	return ErrorCode_NOT_IMPLEMENTED
}

func (m *Error) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type Event struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Event) Reset()         { *m = Event{} }
func (m *Event) String() string { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()    {}
func (*Event) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c5fb4d8cc22d66a, []int{4}
}

func (m *Event) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Event.Unmarshal(m, b)
}
func (m *Event) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Event.Marshal(b, m, deterministic)
}
func (m *Event) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Event.Merge(m, src)
}
func (m *Event) XXX_Size() int {
	return xxx_messageInfo_Event.Size(m)
}
func (m *Event) XXX_DiscardUnknown() {
	xxx_messageInfo_Event.DiscardUnknown(m)
}

var xxx_messageInfo_Event proto.InternalMessageInfo

func init() {
	proto.RegisterEnum("OperationCode", OperationCode_name, OperationCode_value)
	proto.RegisterEnum("ErrorCode", ErrorCode_name, ErrorCode_value)
	proto.RegisterType((*Message)(nil), "Message")
	proto.RegisterType((*Reply)(nil), "Reply")
	proto.RegisterType((*InformationReply)(nil), "InformationReply")
	proto.RegisterType((*Error)(nil), "Error")
	proto.RegisterType((*Event)(nil), "Event")
}

func init() { proto.RegisterFile("schema.proto", fileDescriptor_1c5fb4d8cc22d66a) }

var fileDescriptor_1c5fb4d8cc22d66a = []byte{
	// 522 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x93, 0xd1, 0x6e, 0xda, 0x30,
	0x14, 0x86, 0x29, 0x85, 0x50, 0x0e, 0x50, 0x8c, 0xe9, 0x3a, 0x2e, 0xa6, 0x0a, 0x71, 0x35, 0x55,
	0x53, 0x2f, 0xba, 0x27, 0x48, 0xc9, 0x69, 0xf0, 0x20, 0x0e, 0x73, 0x4c, 0x25, 0x7a, 0x13, 0xa5,
	0xe0, 0x75, 0x48, 0x2d, 0x41, 0x4e, 0xa8, 0xb4, 0x67, 0xda, 0x4b, 0x4e, 0x76, 0x02, 0xed, 0xee,
	0x7c, 0xbe, 0x73, 0xfc, 0xff, 0xe7, 0x4f, 0x64, 0x68, 0x67, 0xab, 0xdf, 0xea, 0x35, 0xb9, 0xd9,
	0xe9, 0x34, 0x4f, 0x47, 0x7b, 0x68, 0x04, 0x2a, 0xcb, 0x92, 0x67, 0x45, 0xbf, 0x40, 0x33, 0xdb,
	0x3c, 0x6f, 0x93, 0x7c, 0xaf, 0xd5, 0xe0, 0x64, 0x78, 0xf2, 0xb5, 0x2d, 0xde, 0x01, 0xbd, 0x04,
	0x27, 0x4b, 0xf7, 0x7a, 0xa5, 0x06, 0x55, 0xdb, 0x2a, 0x2b, 0x3a, 0x84, 0xd6, 0x5a, 0x65, 0xf9,
	0x66, 0x9b, 0xe4, 0x9b, 0x74, 0x3b, 0x38, 0xb5, 0xcd, 0x8f, 0x88, 0x52, 0xa8, 0xad, 0x93, 0x3c,
	0x19, 0xd4, 0x6c, 0xcb, 0x9e, 0x47, 0x53, 0xa8, 0x0b, 0xb5, 0x7b, 0xf9, 0x43, 0x07, 0xe0, 0x68,
	0x95, 0xed, 0x5f, 0xf2, 0xc2, 0x71, 0x52, 0x11, 0x65, 0x4d, 0xaf, 0xa0, 0xae, 0xb4, 0x4e, 0xb5,
	0xf5, 0x6b, 0xdd, 0x3a, 0x37, 0x68, 0xaa, 0x49, 0x45, 0x14, 0xf8, 0xee, 0x0c, 0x9c, 0x2c, 0x4f,
	0xf2, 0x7d, 0x36, 0xfa, 0x06, 0x84, 0x6d, 0x7f, 0xa5, 0xfa, 0xd5, 0xfa, 0x1d, 0x74, 0x1b, 0x6f,
	0x4a, 0x67, 0x66, 0x25, 0x23, 0xdc, 0x14, 0x87, 0x72, 0xc4, 0xa0, 0x6e, 0x95, 0xe8, 0x15, 0xd4,
	0x56, 0xe9, 0xba, 0x88, 0x7a, 0x7e, 0x0b, 0x85, 0xfe, 0x38, 0x5d, 0x2b, 0x61, 0x79, 0x99, 0x6c,
	0xa5, 0x37, 0x3b, 0x9b, 0xac, 0x6a, 0x65, 0x3e, 0xa2, 0x51, 0x03, 0xea, 0xf8, 0xa6, 0xb6, 0xf9,
	0xf5, 0xdf, 0x53, 0xe8, 0x84, 0x3b, 0xa5, 0xed, 0x02, 0x46, 0x82, 0x76, 0xa1, 0xc5, 0xf8, 0x7d,
	0x28, 0x02, 0x57, 0xb2, 0x90, 0x93, 0x0a, 0xed, 0x43, 0x57, 0xa0, 0xcf, 0x22, 0x89, 0x22, 0xf6,
	0xf0, 0x81, 0x8d, 0x91, 0x9c, 0xd0, 0x4b, 0xa0, 0x3e, 0x72, 0x14, 0xae, 0xc4, 0x78, 0x3c, 0x71,
	0x67, 0x33, 0xe4, 0x3e, 0x92, 0x2a, 0xed, 0x40, 0xd3, 0x5d, 0xc8, 0x49, 0x28, 0xd8, 0x23, 0x92,
	0x53, 0xfa, 0x09, 0x7a, 0xc7, 0xbb, 0xcc, 0x43, 0x2e, 0x99, 0x5c, 0x92, 0x1a, 0xed, 0x41, 0x67,
	0xc6, 0xf8, 0xf4, 0x1d, 0xd5, 0x8d, 0xcb, 0x82, 0xff, 0x0f, 0x1d, 0xfa, 0x19, 0xfa, 0x33, 0x16,
	0xc9, 0xd8, 0x70, 0xf4, 0x4a, 0xf7, 0x88, 0x34, 0x8c, 0xc0, 0x62, 0xee, 0x19, 0xf3, 0x72, 0xa3,
	0x33, 0x2b, 0x50, 0xa0, 0xa3, 0x40, 0xd3, 0x84, 0x29, 0xe1, 0x14, 0x97, 0x11, 0x01, 0x7a, 0x01,
	0xe4, 0xe7, 0x02, 0xc5, 0xf2, 0x30, 0xc4, 0x30, 0x22, 0x2d, 0x33, 0x56, 0xd0, 0xf1, 0xc4, 0x95,
	0x11, 0x69, 0x1b, 0x30, 0x16, 0x58, 0x86, 0x93, 0xa4, 0x63, 0x72, 0xfd, 0x08, 0x19, 0x2f, 0xca,
	0x73, 0xe3, 0x3f, 0x47, 0xee, 0x31, 0xee, 0x97, 0x57, 0xba, 0xc6, 0xdf, 0x1c, 0xe3, 0xc0, 0xe5,
	0xae, 0x8f, 0x01, 0x72, 0x49, 0x08, 0x25, 0xd0, 0x8e, 0x90, 0x7b, 0x71, 0x80, 0x51, 0xe4, 0xfa,
	0x48, 0x7a, 0x94, 0xc2, 0x79, 0x61, 0x55, 0xa2, 0x88, 0x50, 0x33, 0x85, 0x1e, 0x93, 0xc7, 0xa9,
	0xbe, 0xf9, 0x6e, 0x26, 0x38, 0xf2, 0xf8, 0x3e, 0x14, 0x31, 0x3e, 0x20, 0x97, 0x11, 0xb9, 0xb8,
	0x1e, 0x42, 0xf3, 0xf8, 0xaf, 0x8d, 0x21, 0x0f, 0x65, 0xcc, 0x82, 0xf9, 0xcc, 0xda, 0xa1, 0x47,
	0x2a, 0x77, 0xb5, 0xc7, 0xea, 0xee, 0xe9, 0xc9, 0xb1, 0x4f, 0xe4, 0xfb, 0xbf, 0x00, 0x00, 0x00,
	0xff, 0xff, 0xbb, 0x58, 0xa0, 0x2f, 0x32, 0x03, 0x00, 0x00,
}
